import './globals.css'
import { Inter } from 'next/font/google'
import NavMenu from '../components/nav-menu'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${styles.rootLayout} ${inter.className}`}>
        <header>
          <NavMenu />
        </header>
        <main>
          {children}
        </main>
        <footer>Created by Kirstin Penzes, powered by React+Next.js</footer>
        </body>
    </html>
  )
}
